Nc news 11
hjaox/be-nc-news pull request #11
Opened 2023-08-16 10:53 UTC by hjaox

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit requested changes
Good testing! Some missing tests however:
- What do you expect if the request query gives an invalid _sort_by_ ?
- What do you expect if the request query gives an invalid _order_ ?
- What do you expect if the _topic_ can't be found in the database ?
- What do you expect if the _topic_ was found in the database but has no _articles_ ?

Add these tests, they may require you to refactor your model and how you handle _sort_by_ and _order_ then submit another PR

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                })
This is a good test!

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                        expect(article.topic).toMatch(/MiTcH/i);
This assertion is being run on the response so you could assert `expect(article.topic).toBe("mitch")` again

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                    expect(articles.length).not.toBe(0);
Could be more precise here by asserting for the specific length you expect it to be, remember that the test data should always remain constant so there's no reason to expect the length to ever change

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                    expect(articles).toEqual(articles.sort((a,b) => b.title - a.title));
You can remove line _127_ as it's only doing the same thing as line _126_ but long hand

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                    expect(articles).toEqual(articles.sort((a,b) => b.article_id - a.article_id));
could remove line _148_ as it's just a long hand repetition of line _147_

2023-08-16 11:29 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                    expect(articles).toBeSortedBy('article_id', {ascending: true});
Looking at the docs I think you might want this to be `('article_id', { descending: false});` rather than _ascending: true_

2023-08-17 10:51 UTC, Keb84 approved these changes
Nice work amending your code from the feedback 🙂 merge when ready 👍

2023-08-17 10:54 UTC, merged